[ui]
agent_panel_sort = "priority"

show_agent_labels_on_pane_borders = true
[keys]
prefix = "ctrl+a"

# Switch tabs with Ctrl+[ (previous) and Ctrl+] (next)
previous_tab = "ctrl+["
next_tab = "ctrl+]"

# Switch agents with cmd+ctrl+[ / ]
previous_agent = "cmd+ctrl+["
next_agent = "cmd+ctrl+]"

# Switch workspaces with cmd+shift+ctrl+[ / ]
previous_workspace = "cmd+shift+ctrl+["
next_workspace = "cmd+shift+ctrl+]"

# [[keys.command]] # lazygit：分屏打开
# key = "prefix+g"
# type = "plugin_action"
# command = "herdr-lazygit.open"

[[keys.command]] # lazygit：独立 tab 打开
key = "prefix+g"
type = "plugin_action"
command = "herdr-lazygit.open-tab"

# Optional: Focus Tabs/Panes/Agents when open navigator
[[keys.command]]
key = "cmd+i"
type = "plugin_action"
command = "beyondlex.herdr-recent-navigator.focus-tabs"
description = "Open Navigator: Tab"

[[keys.command]] # open in a split pane
key = "prefix+y"
type = "plugin_action"
command = "ray.file-explorer.open"
description = "open file explorer"

[[keys.command]] # open in a new tab
key = "prefix+Y"
type = "plugin_action"
command = "ray.file-explorer.open-tab"
description = "open file explorer in a new tab"

# 显式声明深色主题
[theme]
name = "catppuccin"

[ui.toast]
delivery = "herdr"

[experimental]
kitty_graphics = true
